### ISSUE TITLE
problem installing in iojs

### ISSUE THREAD

**Issue by mderazon** [bnoordhuis/node-unix-dgram#22]
```
gyp ERR! build error
gyp ERR! stack Error: not found: make
gyp ERR! stack     at F (/home/ubuntu/.nvm/versions/io.js/v1.6.4/lib/node_modules/npm/node_modules/which/which.js:40:28)
gyp ERR! stack     at E (/home/ubuntu/.nvm/versions/io.js/v1.6.4/lib/node_modules/npm/node_modules/which/which.js:43:29)
gyp ERR! stack     at /home/ubuntu/.nvm/versions/io.js/v1.6.4/lib/node_modules/npm/node_modules/which/which.js:54:16
gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:77:15)
gyp ERR! System Linux 3.13.0-49-generic
gyp ERR! command "/home/ubuntu/.nvm/versions/io.js/v1.6.4/bin/iojs" "/home/ubuntu/.nvm/versions/io.js/v1.6.4/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/ubuntu/.pm2/node_modules/pm2-syslog/node_modules/ain2/node_modules/unix-dgram
gyp ERR! node -v v1.6.4
gyp ERR! node-gyp -v v1.0.3
gyp ERR! not ok
npm WARN optional dep failed, continuing unix-dgram@0.1.2
```

iojs/io.js#456

**Comment by bnoordhuis** [comment]
It has nothing to do with io.js, you need to `apt-get install build-essential`.

**Comment by mderazon** [comment]
you are correct..
had other problems later trying to install `v0.1.1` but then it went smooth with `v0.1.2`

sorry for that, and thanks :+1:
