### ISSUE TITLE
does not work on node 4 or node 5

### ISSUE THREAD

**Issue by Ilya1st** [bnoordhuis/node-unix-dgram#31]
server.js pid 12484
/usr/lib/node_modules/unix-dgram/node_modules/bindings/bindings.js:83
        throw e
        ^

Error: Module did not self-register.
    at Error (native)
    at Object.Module._extensions..node (module.js:450:18)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at bindings (/usr/lib/node_modules/unix-dgram/node_modules/bindings/bindings.js:76:44)
    at Object.<anonymous> (/usr/lib/node_modules/unix-dgram/lib/unix_dgram.js:4:34)
    at Module._compile (module.js:425:26)
    at Object.Module._extensions..js (module.js:432:10)

This occures when I do require('unix-dgram');
I've looked inside bindings.js - it does find binary file node_modules/unix-dgram/build/Release/unix_dgram.node but tells that module is not registered.

**Comment by santigimeno** [comment]
It looks like you haven't rebuilt the module with the new versions. Try `npm rebuild`.

**Comment by santigimeno** [comment]
Closing. Feel free to reopen if it's still an issue.
