### ISSUE TITLE
getting a "make" error when building on CentOS 7

### ISSUE THREAD

**Issue by cwysong85** [bnoordhuis/node-unix-dgram#32]
I'm using a library called `winston-syslog` that requires your library as a dependency. When running `node-gyp rebuild`, make gets an error.

FYI I have all the Development Tools installed.

```
$ node-gyp rebuild
gyp info it worked if it ends with ok
gyp info using node-gyp@3.1.0
gyp info using node@0.11.14 | linux | x64
gyp info spawn python2
gyp info spawn args [ '/usr/lib/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/root/node-unix-dgram/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/usr/lib/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/root/.node-gyp/0.11.14/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/root/.node-gyp/0.11.14',
gyp info spawn args   '-Dnode_gyp_dir=/usr/lib/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=node.lib',
gyp info spawn args   '-Dmodule_root_dir=/root/node-unix-dgram',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.' ]
gyp info spawn make
gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
make: Entering directory `/root/node-unix-dgram/build'
  CXX(target) Release/obj.target/unix_dgram/src/unix_dgram.o
In file included from ../src/unix_dgram.cc:5:
../node_modules/nan/nan.h: In function 'void Nan::SetCounterFunction(int* (*)(const char*))':
../node_modules/nan/nan.h:447: error: 'class v8::Isolate' has no member named 'SetCounterFunction'
../node_modules/nan/nan.h: In function 'void Nan::SetCreateHistogramFunction(void* (*)(const char*, int, int, size_t))':
../node_modules/nan/nan.h:452: error: 'class v8::Isolate' has no member named 'SetCreateHistogramFunction'
../node_modules/nan/nan.h: In function 'void Nan::SetAddHistogramSampleFunction(void (*)(void*, int))':
../node_modules/nan/nan.h:457: error: 'class v8::Isolate' has no member named 'SetAddHistogramSampleFunction'
../node_modules/nan/nan.h: In function 'bool Nan::IdleNotification(int)':
../node_modules/nan/nan.h:468: error: 'class v8::Isolate' has no member named 'IdleNotification'
../node_modules/nan/nan.h: In function 'void Nan::LowMemoryNotification()':
../node_modules/nan/nan.h:473: error: 'class v8::Isolate' has no member named 'LowMemoryNotification'
../node_modules/nan/nan.h: In function 'void Nan::ContextDisposedNotification()':
../node_modules/nan/nan.h:477: error: 'class v8::Isolate' has no member named 'ContextDisposedNotification'
make: *** [Release/obj.target/unix_dgram/src/unix_dgram.o] Error 1
make: Leaving directory `/root/node-unix-dgram/build'
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/node-gyp/lib/build.js:270:23)
gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1059:12)
gyp ERR! System Linux 2.6.32-504.16.2.el6.x86_64
gyp ERR! command "node" "/usr/bin/node-gyp" "rebuild"
gyp ERR! cwd /root/node-unix-dgram
gyp ERR! node -v v0.11.14
gyp ERR! node-gyp -v v3.1.0
gyp ERR! not ok
```

**Comment by bnoordhuis** [comment]
> gyp ERR! node -v v0.11.14

You should update your copy of node.  v0.11.14 is an old development release.

**Comment by santigimeno** [comment]
Closing. Feel free to reopen if it's still an issue
