### ISSUE TITLE
- sorry -

### ISSUE THREAD

**Issue by jbdemonte** [bnoordhuis/node-unix-dgram#40]
sorry - my fault -

**Comment by jbdemonte** [comment]
And in fact, if you try to connect the client on a socket not yet created by the server, this is the same problem, and the is no way to try to catch it using a:

    try {
        socket.connect(socketPath);
    } catch (err) {
        console.log("never called");
    }

The process simply exit:


    jbd@ns3049818:~/test_socket$ node client.js
    { Error: connect -111
      at errnoException (/home/jbd/test_socket/node_modules/unix-dgram/lib/unix_dgram.js:18:11)
      at Socket.connect (/home/jbd/test_socket/node_modules/unix-dgram/lib/unix_dgram.js:75:24)
      at Object.<anonymous> (/home/jbd/test_socket/client.js:31:12)
      at Module._compile (module.js:571:32)
      at Object.Module._extensions..js (module.js:580:10)
      at Module.load (module.js:488:32)
      at tryModuleLoad (module.js:447:12)
      at Function.Module._load (module.js:439:3)
      at Module.runMain (module.js:605:10)
      at run (bootstrap_node.js:420:7) code: -111, errno: -111, syscall: 'connect' }
