### ISSUE TITLE
Error | Failing build unix-dgram on solaris

### ISSUE THREAD

**Issue by usebaz** [bnoordhuis/node-unix-dgram#45]
When I try build unix-dragm on solaris, it failing.
Run cmd: `node-gyp configure` and `node-gyp build`.
Output:
```
-> % node-gyp configure                                                               
gyp info it worked if it ends with ok
gyp info using node-gyp@3.6.0
gyp info using node@6.9.1 | sunos | x64
gyp info spawn /usr/bin/python
gyp info spawn args [ '/usr/node/lib/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/tmp/node-unix-dgram/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/usr/node/lib/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/export/home/akuzmenko/.node-gyp/6.9.1/include/node/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/export/home/akuzmenko/.node-gyp/6.9.1',
gyp info spawn args   '-Dnode_gyp_dir=/usr/node/lib/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=node.lib',
gyp info spawn args   '-Dmodule_root_dir=/tmp/node-unix-dgram',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.' ]
gyp info ok 
```
```
-> % node-gyp build                
gyp info it worked if it ends with ok
gyp info using node-gyp@3.6.0
gyp info using node@6.9.1 | sunos | x64
gyp info spawn make
gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
make: Entering directory `/tmp/node-unix-dgram/build'
  CXX(target) Release/obj.target/unix_dgram/src/unix_dgram.o
../src/unix_dgram.cc: In function 'void {anonymous}::OnRecv({anonymous}::SocketContext*)':
../src/unix_dgram.cc:86:24: error: expected unqualified-id before numeric constant
     struct sockaddr_un sun;
                        ^
../src/unix_dgram.cc:95:10: error: expected unqualified-id before numeric constant
   u_addr.sun.sun_path[0] = '\0';
          ^
../src/unix_dgram.cc:95:10: error: expected ';' before numeric constant
../src/unix_dgram.cc:111:16: error: expected unqualified-id before numeric constant
     if (u_addr.sun.sun_path[0] != '\0') {
                ^
../src/unix_dgram.cc:111:16: error: expected ')' before numeric constant
../src/unix_dgram.cc:112:41: error: expected unqualified-id before numeric constant
       argv[2] = Nan::New<String>(u_addr.sun.sun_path).ToLocalChecked();
                                         ^
make: *** [Release/obj.target/unix_dgram/src/unix_dgram.o] Error 1
make: Leaving directory `/tmp/node-unix-dgram/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/node/lib/node_modules/node-gyp/lib/build.js:285:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
gyp ERR! System SunOS 5.11
gyp ERR! command "/usr/node/bin/node" "/usr/node/bin/node-gyp" "build"
gyp ERR! cwd /tmp/node-unix-dgram
gyp ERR! node -v v6.9.1
gyp ERR! node-gyp -v v3.6.0
gyp ERR! not ok 
```

Packages:
```
-> % make -v
GNU Make 3.82
Built for i386-pc-solaris2.11
Copyright (C) 2010  Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
```
```
-> % gcc -v 
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/gcc/4.8/lib/gcc/i386-pc-solaris2.11/4.8.2/lto-wrapper
Target: i386-pc-solaris2.11
Configured with: /builds/hudson/workspace/nightly-update/build/i386/components/gcc48/gcc-4.8.2/configure CC=/usr/gcc/4.7/bin/gcc CXX=/usr/gcc/4.7/bin/g++ --prefix=/usr/gcc/4.8 --mandir=/usr/gcc/4.8/share/man --bindir=/usr/gcc/4.8/bin --libdir=/usr/gcc/4.8/lib --sbindir=/usr/gcc/4.8/sbin --infodir=/usr/gcc/4.8/share/info --libexecdir=/usr/gcc/4.8/lib --enable-languages=c,c++,fortran,objc --enable-shared --with-gmp-include=/usr/include/gmp --with-mpfr-include=/usr/include/mpfr --without-gnu-ld --with-ld=/usr/bin/ld --with-gnu-as --with-as=/usr/gnu/bin/as CFLAGS='-g -O2  -mtune=opteron -march=opteron' CXXFLAGS='-g -O2 -mtune=opteron -march=opteron'
Thread model: posix
gcc version 4.8.2 (GCC) 
```

**Comment by bnoordhuis** [comment]
You can probably fix it by renaming the variable, I bet it's conflicting with a system header or define.  Open a pull request if you get it working.

**Comment by usebaz** [comment]
@bnoordhuis yes with different name it build ok. Which name is better to rename?

**Comment by bnoordhuis** [comment]
No strong opinion.  Just `s` would be fine.

**Comment by usebaz** [comment]
@bnoordhuis done.
Also, can you release version 0.2.4 in npm with this changes?
